apiVersion: skaffold/v2beta29
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  tagPolicy:
    gitCommit: {}
  local:
    push: false
  artifacts:
    - image: vlad246/tms-orders
      context: tms
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: vlad246/tms-dashboard
      context: tms-dashboard
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
# TODO: Create a way to test on the database on testing the services
# test:
#   - image: vlad246/tms-orders
#     context: tms
#     custom:
#       - command: ./test.sh
