apiVersion: skaffold/v2beta29
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  tagPolicy:
    gitCommit: {}
  local:
    push: false
  artifacts:
    - image: vlad246/tms-orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
# TODO: Create a way to test on the database on testing the services
test:
  - image: vlad246/tms-orders
    context: orders
    custom:
      - command: ./test.sh
