apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  init.sql: |
    CREATE USER hermestms WITH PASSWORD 'hermestmspw';
    GRANT ALL PRIVILEGES ON DATABASE tms2 TO hermestms;